version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      TZ: America/Sao_paulo
    ports:
      - '4431:5432'
    restart: always
    volumes:
      - ~/.parti-notes:/var/lib/postgresql/data
